### PR TITLE
logging abstraction

### PR DESCRIPTION
**Pull request by elifitch**
Sorry this took so long!

### CODE REVIEW

**Comment by batpad** [comment]
This looks good to me @elifitch !

Can we:

 - Establish a strong convention to distinguish between "system logs" or so and between "user activity logs" - I imagine we'd be using both those log types for vastly different purposes.
 - Switch to outputting JSON by default

**Comment by elifitch** [comment]
@batpad so what I did there, is I added a flag to allow us to export the log, or keep it internal.  They all go to `stdout`, but they'll be super easy to filter this way.  They're also outputting in json now

**Comment by elifitch** [comment]
@batpad We've got kinesis logging going now, controllable by an environment variable `ENABLE_KINESIS_LOGGING`

This should be good to review now

**Comment by batpad** [comment]
@elifitch this looks great to me!

Per chat, it'd be great to be able to send arbitrary objects to the logger instead of just strings and the logger should merge the log object keys with the default keys.

Apart from that, it would be great to have some basic tests, mostly to double up as documentation on usage, but I wouldn't consider that a blocker to merge right now.

**Comment by batpad** [comment]
Hmm it also seems like `Travis` doesn't like some of the es6 syntax we're using here. Can you tell what version you're using locally? We can probably ask Travis to use the same version to run tests and we can make sure we're using the same version in deployments.

**Comment by elifitch** [comment]
@batpad fixed that es6 issue upstream, added ability to send arbitrary data through the logger. Travis build is now breaking because of a hard dependency on an environment variable pointing to a kinesis firehose.  I need to add in graceful regression to console.log

**Comment by elifitch** [comment]
@batpad builds passing

**Comment by batpad** [comment]
@elifitch you can add any environment variables that Travis needs here, if that makes things any better: https://github.com/osmlab/to-fix-backend/blob/master/.travis.yml#L7

**Comment by batpad** [comment]
Feel free to merge @elifitch !

**Comment by elifitch** [comment]
Tests written; merging

**Pull request merged**
