### PR TITLE
Improving  to-fix-backend

### PR DESCRIPTION
**Pull request by Rub21**
Some progress here, improving to-fix-backend and supporting geojson files.   
-  Use postgres JSONB to store a project, task and items.
- We can add an unlimited number of fields as we want for project, tasks  and items, without any modification in DB
- To create a task ,first we need to create a project as a parent, the project  may contain many tasks and each task is creating using a geojson file and other required fields.
- CRUD for project and tasks.
- Better documentation for the API routes.
- Throw a request to get and set the action  for a item and get a new item as response.
- Update the stats for each task, on every request, it not affect the process to get  a new item faster.
- Save the stats for each task, this will be much faster and less expensive as we do now.
- Load a geojson file in a child process(do other DB connection), it not effect the API performance. 

**What we need to improve so far?**
- The way to load  each geojson feature in the row  in postgres table.
- Update an exiting  tasks, (basically need to work on postgres tables).

**Add more functionalities.**
- Create activity functionality like http://osmlab.github.io/to-fix/#/activity/crossingmajorhighways.
- Stats for each user and tasks http://osmlab.github.io/to-fix/#/stats/crossingmajorhighways
- Download the geojson file of a task with all activity (edition, fixed, noterror) per each item.
- Creating  tests for API.

I am still working in more functionality and  improving some process, any help will be welcome to improve that.

cc. @aaronlidman @batpad @ajithranka @planemad @maning  @geohacker

### CODE REVIEW

**Comment by aaronlidman** [comment]
Great start Ruben.

> The way to load each geojson feature in the row in postgres table.

I see this as the most important thing. It must be fast to upload tens of thousands of items.

> Download the geojson file of a task with all activity (edition, fixed, noterror) per each item.

Sounds cool, but I don't think this is a huge priority.

Great job so far, thanks for taking this on.

**Comment by Rub21** [comment]
### Some Progress here:

What functionalities have I added?
- Track the users activity.
- Output for all users activity in a task.
- Output for a specific user activity in a task.
- Output stats for each task as we did in to-fix.
- backup of previous items of table in a file, whenever we update a task save the backup in a file. and add the link of this file in the history of task,together with the stats's history.
- Add a other fields to create a project and a task.
- Fixing some inconsistent function.

Want we need to improve?
- Improve the way to save the features into DB. I've been trying with pg-copy-streams, parsing the geojson file however it works slow as well. looking other way to improve this process. 

What we need to add?
- Add authentication and support session  for to-fix-backend?
- Language support.(not really important for now)
- support to upload a image for a project

All routes:
image

cc. @aaronlidman @batpad

**Comment by ajithranka** [comment]
It will also be useful to be able to set an arbitrary configuration object for tasks. Possible configurations might include:
- Default map settings like map style, initial zoom etc.
- Plugins to include (mapillary, for instance) and related configurations

This could be part of the `/tasks` payload or a separate route:

```
GET /tasks/{idtask}/config
POST /tasks/{idtask}/config
```

**Comment by ajithranka** [comment]
@Rub21 Should we close this PR?

**Comment by Rub21** [comment]
close this!

**Pull request closed without merging**
